### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by marquez138** [moltin/gatsby-demo-store#102]
Hi getting this error trying to build and deploy on Netlify :

ReferenceError: window is not defined
     at /opt/build/repo/public/render-page.js:54610:18
     at Fa (/opt/build/repo/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:28:265)
     at Object.useState (/opt/build/repo/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:31:35)
     at useState (/opt/build/repo/node_modules/react/cjs/react.production.min.js:23:312)
     at useLocalStorage (/opt/build/repo/public/render-page.js:54608:73)
     at CustomerProvider (/opt/build/repo/public/render-page.js:54241:91)
     at d (/opt/build/repo/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:498)
     at Za (/opt/build/repo/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
     at a.b.render (/opt/build/repo/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
     at a.b.read (/opt/build/repo/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
     at renderToString (/opt/build/repo/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
     at Module../.cache/static-entry.js.__webpack_exports__.default (/opt/build/repo/public/render-page.js:835:18)
     at Promise (/opt/build/repo/node_modules/gatsby/dist/utils/worker/render-html.js:35:36)
    at Promise._execute (/opt/build/repo/node_modules/bluebird/js/release/debuggability.js:313:9)
     at Promise._resolveFromExecutor (/opt/build/repo/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/opt/build/repo/node_modules/bluebird/js/release/promise.js:79:10)

Looking at the other errors it seems to be apparent to the hooks (useState ,etc)? Any idea how i can fix this? 

Thanks again

**Comment by marquez138** [comment]
Hi was checking to see if any solution could help resolve this issue? Would really like to use to use moltin for my project

**Comment by notrab** [comment]
@marquez138 the "error" (although it won't fail a build) will be coming from the [`useLocalStorage`](https://github.com/moltin/gatsby-demo-store/blob/master/src/context/useLocalStorage.js#L6) hook.

This file will need updating to have a conditional check for `window === undefined` and if so, do nothing.

**Comment by marquez138** [comment]
hey guys thanks again for the reply

Just to make sure i understand, dont do anything on my end? Sorry still learning

**Comment by notrab** [comment]
@marquez138 you could create a PR to fix it if you wanted to, but the error shouldn't stop you doing what you're doing. It's more of a Gatsby warning that window isn't available SSR.

**Comment by marquez138** [comment]
Great deployed to netlify thanks again!
