### ISSUE TITLE
Same issue as @cn2amz

### ISSUE THREAD

**Issue by iamnex** [moltin/gatsby-demo-store#17]
I have the same problem. Even if I add the client id in .env file or in gatsby-config.js directly doesn't work and give the same errors like @cn2amz . Can anyone help?

**Comment by ynnoj** [comment]
@iamnex Do you have products in your Moltin store?

**Comment by iamnex** [comment]
Yes.

**Comment by iamnex** [comment]
Here is the output for yarn dev :






MacBook-Pro-Ionut:gatsby-demo-store ionut$ yarn dev
yarn run v1.17.0
$ rimraf .cache && gatsby develop
success open and validate gatsby-configs - 0.016 s
success load plugins - 0.286 s
success onPreInit - 0.757 s
success delete html and css files from previous builds - 0.015 s
success initialize cache - 0.014 s
success copy gatsby files - 0.073 s
success onPreBootstrap - 0.009 s
error Plugin @moltin/gatsby-source-moltin returned an error


  TypeError: Cannot destructure property `main_images` of 'undefined' or 'null'.
  
  - gatsby-node.js:128 Object.exports.sourceNodes
    [gatsby-demo-store]/[@moltin]/gatsby-source-moltin/gatsby-node.js:128:7
  
  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7
  

warn The @moltin/gatsby-source-moltin plugin has generated no Gatsby nodes. Do you need it?
success source and transform nodes - 2.339 s
success building schema - 0.289 s
error gatsby-node.js returned an error


  TypeError: Cannot read property 'allProducts' of undefined
  
  - gatsby-node.js:26 Object.exports.createPages
    /Users/ionut/Desktop/gatsby-demo-store/gatsby-node.js:26:14
  

success createPages - 0.023 s
success createPagesStatefully - 0.051 s
success onPreExtractQueries - 0.005 s
success update schema - 0.117 s
error GraphQL Error There was an error while compiling your site's GraphQL queries.
  Error: RelayParser: Encountered 5 error(s):
- Unknown field 'allMoltinCategory' on type 'Query'. Source: document `SiteTitleQuery` file: `GraphQL request`

  GraphQL request (8:5)
  7:     }
  8:     allMoltinCategory {
         ^
  9:       edges {

- Unknown field 'allMoltinCategory' on type 'Query'. Source: document `IndexPageQuery` file: `GraphQL request`

  GraphQL request (3:5)
  2:   query IndexPageQuery {
  3:     categories: allMoltinCategory {
         ^
  4:       edges {

- Unknown field 'allMoltinProduct' on type 'Query'. Source: document `allProductsQuery` file: `GraphQL request`

  GraphQL request (3:5)
  2:   query allProductsQuery {
  3:     allMoltinProduct {
         ^
  4:       edges {

- Unknown field 'moltinCategory' on type 'Query'. Source: document `usersIonutDesktopGatsbyDemoStoreSrcTemplatesCategoryPageJs373371444` file:
`GraphQL request`

  GraphQL request (3:5)
  2:   query($id: String!) {
  3:     category: moltinCategory(id: { eq: $id }) {
         ^
  4:       id

- Unknown field 'moltinProduct' on type 'Query'. Source: document `usersIonutDesktopGatsbyDemoStoreSrcTemplatesProductPageJs1878776835` file:
`GraphQL request`

  GraphQL request (3:5)
  2:   query($id: String!) {
  3:     product: moltinProduct(id: { eq: $id }) {
         ^
  4:       id
success extract queries from components - 0.114 s
success run graphql queries - 0.027 s — 7/7 312.10 queries/second
success write out page data - 0.011 s
success write out redirect data - 0.003 s
done generating icons for manifest
success onPostBootstrap - 0.124 s
⠀
info bootstrap finished - 9.494 s
⠀
 ERROR  Failed to compile with 4 errors                                                                                                   3:59:08 PM
⠀
 error  in ./src/components/Layout/Layout.js
⠀
Module Error (from ./node_modules/eslint-loader/index.js):

/Users/ionut/Desktop/gatsby-demo-store/src/components/Layout/Layout.js
  33:5  error  Cannot query field "allMoltinCategory" on type "Query"  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)


 @ ./src/components/Layout/index.js 5:0-35 5:0-35
 @ ./gatsby-browser.js
 @ ./.cache/api-runner-browser-plugins.js
 @ ./.cache/api-runner-browser.js
 @ ./.cache/app.js
 @ multi event-source-polyfill (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app
⠀
 error  in ./src/pages/index.js
⠀
Module Error (from ./node_modules/eslint-loader/index.js):

/Users/ionut/Desktop/gatsby-demo-store/src/pages/index.js
  51:5  error  Cannot query field "allMoltinCategory" on type "Query"  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)


 @ ./.cache/sync-requires.js 23:54-122
 @ ./.cache/app.js
 @ multi event-source-polyfill (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app
⠀
 error  in ./src/pages/products.js
⠀
Module Error (from ./node_modules/eslint-loader/index.js):

/Users/ionut/Desktop/gatsby-demo-store/src/pages/products.js
  20:5  error  Cannot query field "allMoltinProduct" on type "Query"  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)


 @ ./.cache/sync-requires.js 24:57-128
 @ ./.cache/app.js
 @ multi event-source-polyfill (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app
⠀
 error  in ./src/components/CartItem.js
⠀
Module build failed (from ./node_modules/eslint-loader/index.js):
Error: VariableDeclarator ASTNodes are not handled by markPropTypesAsUsed
Occurred while linting /Users/ionut/Desktop/gatsby-demo-store/src/components/CartItem.js:17
    at markPropTypesAsUsed (/Users/ionut/Desktop/gatsby-demo-store/node_modules/eslint-plugin-react/lib/util/usedPropTypes.js:338:15)
    at Object.VariableDeclarator (/Users/ionut/Desktop/gatsby-demo-store/node_modules/eslint-plugin-react/lib/util/usedPropTypes.js:492:9)
    at updatedRuleInstructions.(anonymous function)
(/Users/ionut/Desktop/gatsby-demo-store/node_modules/eslint-plugin-react/lib/util/Components.js:780:47)
    at listeners.(anonymous function).forEach.listener (/Users/ionut/Desktop/gatsby-demo-store/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/ionut/Desktop/gatsby-demo-store/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/ionut/Desktop/gatsby-demo-store/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/ionut/Desktop/gatsby-demo-store/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/ionut/Desktop/gatsby-demo-store/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/Users/ionut/Desktop/gatsby-demo-store/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:632:23)
    at nodeQueue.forEach.traversalInfo (/Users/ionut/Desktop/gatsby-demo-store/node_modules/eslint/lib/linter.js:752:32)
    at Array.forEach (<anonymous>)
    at runRules (/Users/ionut/Desktop/gatsby-demo-store/node_modules/eslint/lib/linter.js:747:15)
    at Linter._verifyWithoutProcessors (/Users/ionut/Desktop/gatsby-demo-store/node_modules/eslint/lib/linter.js:899:31)
    at preprocess.map.textBlock (/Users/ionut/Desktop/gatsby-demo-store/node_modules/eslint/lib/linter.js:955:35)

 @ ./src/components/CartItemList.js 14:0-34 27:31-39
 @ ./src/pages/cart.js
 @ ./.cache/sync-requires.js
 @ ./.cache/app.js
 @ multi event-source-polyfill (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app
⠀
✖ ｢wdm｣:
ERROR in ./src/components/Layout/Layout.js
Module Error (from ./node_modules/eslint-loader/index.js):

/Users/ionut/Desktop/gatsby-demo-store/src/components/Layout/Layout.js
  33:5  error  Cannot query field "allMoltinCategory" on type "Query"  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)

 @ ./src/components/Layout/index.js 5:0-35 5:0-35
 @ ./gatsby-browser.js
 @ ./.cache/api-runner-browser-plugins.js
 @ ./.cache/api-runner-browser.js
 @ ./.cache/app.js
 @ multi event-source-polyfill (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app

ERROR in ./src/pages/index.js
Module Error (from ./node_modules/eslint-loader/index.js):

/Users/ionut/Desktop/gatsby-demo-store/src/pages/index.js
  51:5  error  Cannot query field "allMoltinCategory" on type "Query"  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)

 @ ./.cache/sync-requires.js 23:54-122
 @ ./.cache/app.js
 @ multi event-source-polyfill (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app

ERROR in ./src/pages/products.js
Module Error (from ./node_modules/eslint-loader/index.js):

/Users/ionut/Desktop/gatsby-demo-store/src/pages/products.js
  20:5  error  Cannot query field "allMoltinProduct" on type "Query"  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)

 @ ./.cache/sync-requires.js 24:57-128
 @ ./.cache/app.js
 @ multi event-source-polyfill (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app

ERROR in ./src/components/CartItem.js
Module build failed (from ./node_modules/eslint-loader/index.js):
Error: VariableDeclarator ASTNodes are not handled by markPropTypesAsUsed
Occurred while linting /Users/ionut/Desktop/gatsby-demo-store/src/components/CartItem.js:17
    at markPropTypesAsUsed (/Users/ionut/Desktop/gatsby-demo-store/node_modules/eslint-plugin-react/lib/util/usedPropTypes.js:338:15)
    at Object.VariableDeclarator (/Users/ionut/Desktop/gatsby-demo-store/node_modules/eslint-plugin-react/lib/util/usedPropTypes.js:492:9)
    at updatedRuleInstructions.(anonymous function)
(/Users/ionut/Desktop/gatsby-demo-store/node_modules/eslint-plugin-react/lib/util/Components.js:780:47)
    at listeners.(anonymous function).forEach.listener (/Users/ionut/Desktop/gatsby-demo-store/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/ionut/Desktop/gatsby-demo-store/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/ionut/Desktop/gatsby-demo-store/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/ionut/Desktop/gatsby-demo-store/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/ionut/Desktop/gatsby-demo-store/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/Users/ionut/Desktop/gatsby-demo-store/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:632:23)
    at nodeQueue.forEach.traversalInfo (/Users/ionut/Desktop/gatsby-demo-store/node_modules/eslint/lib/linter.js:752:32)
    at Array.forEach (<anonymous>)
    at runRules (/Users/ionut/Desktop/gatsby-demo-store/node_modules/eslint/lib/linter.js:747:15)
    at Linter._verifyWithoutProcessors (/Users/ionut/Desktop/gatsby-demo-store/node_modules/eslint/lib/linter.js:899:31)
    at preprocess.map.textBlock (/Users/ionut/Desktop/gatsby-demo-store/node_modules/eslint/lib/linter.js:955:35)
    at Array.map (<anonymous>)
 @ ./src/components/CartItemList.js 14:0-34 27:31-39
 @ ./src/pages/cart.js
 @ ./.cache/sync-requires.js
 @ ./.cache/app.js
ℹ ｢wdm｣: Failed to compile.

**Comment by notrab** [comment]
Are the products set to `live`?

**Comment by iamnex** [comment]
Yes. only thing is not set are Brands. Collections are set also Categories are set.

<img width="1186" alt="Screenshot 2019-06-24 at 16 20 54" src="https://user-images.githubusercontent.com/2852685/60022263-2917c900-969c-11e9-9f78-991d52fa129f.png">

**Comment by iamnex** [comment]
Added product images, brands and still got the same error.

**Comment by ynnoj** [comment]
You've no `main_image` relationships on your products.

This demo site is using an older version of `gatsby-source-moltin`. If you bump that dependency it'll be fixed.
